export const PRODUCT_DATA='PRODUCT_DATA';
export const CART_PRODUCT='CART_PRODUCT';
export const ADD_CART='ADD_CART';
export const DELETE_CART='DELETE_CART';
export const UPDATE_CART_TANG='UPDATE_CART_TANG';
export const UPDATE_CART_GIAM='UPDATE_CART_GIAM';